<a href="https://colab.research.google.com/github/jhmartel/fp/blob/master/_notebooks/2022-03-22-Comment_NumerixS_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# "Comments on NumerixS Quiz. "
> "Just reflection ..."
 
- toc: false
- branch: master
- badges: true
- comments: true
- categories: [NumerixS]
- hide: true
- search_exclude: true

Comments on the Ten Question, Multiple Choice, 40 minute quiz from NumerixS. 

JHM: Fair test! Although I always find a way to disagree with some of the answers, if I and we could 'show our work', then we could resolve the confusion and even agree on the answer. 

The time limit is interesting, allowing for four minutes per question. Of course, if we had ten minutes per question then we would have ample time.

For example, you might have a bug who lives on the vertices $A,B,C,D$ of a tetrahedron. The bug moves randomly from vertex $A$ to vertices $B,C,D$; and from those vertices the bug moves randomly again. So what is the probability that after five steps, the bug begins at $A$ and terminates at $A$ ? 

If $X_t$ is the random variable which is the vertex position of the bug after $t$ time steps, then we seek $P(X_4=A | X_0=A)$. I.e. we have the initial condition $X_0=A$. (Notice the time-step index is shifted by -1). This is known as a basic Markov process with probability transition matrix $$A:=\frac{1}{3} \begin{pmatrix} 0 & 1 & 1 & 1 \\
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\
1 & 1 & 1 & 0 \\
\end{pmatrix}.$$

The desired probability $P(X_4=A | X_0=A)$ is then related to the entries of $A^4$, or more specifically, the product $$e_1. A^4. ({}^t e_1).$$ In coordinates this term is equal to the $(1,1)$ entry in the matrix $A^4$. We had a pencil and paper so we computed the first two powers, guessed a recursive formula, then picked the nearest multiple choice answer.

In [ ]:
# collapse

import numpy as np
A = np.array([[0,1,1,1], [1,0,1,1],[1,1,0,1],[1,1,1,0]])
A=[1/3]*A
A4=A@(A@(A@A));
print("The transition matrix A is:\n",A)
print("The fourth power A**4 is:\n",A4)
print("The specific probability of the bug returning to it's initial vertex after five steps is equal to: \n", A4[0,0])

The transition matrix A is:
 [[0.         0.33333333 0.33333333 0.33333333]
 [0.33333333 0.         0.33333333 0.33333333]
 [0.33333333 0.33333333 0.         0.33333333]
 [0.33333333 0.33333333 0.33333333 0.        ]]
The fourth power A**4 is:
 [[0.25925926 0.24691358 0.24691358 0.24691358]
 [0.24691358 0.25925926 0.24691358 0.24691358]
 [0.24691358 0.24691358 0.25925926 0.24691358]
 [0.24691358 0.24691358 0.24691358 0.25925926]]
The specific probability of the bug returning to it's initial vertex after five steps is equal to: 
 0.25925925925925924


Was there a simpler way to determine the coefficient? I don't know.

There's other questions to comment on, but I'll keep this short.

-JHM.